version: '3.3'

services:
  last-civilization_vault:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    image: vault:1.11.2
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id last-civilization
  last-civilization_vault_setup:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    image: vault:1.11.2
    environment:
      - VAULT_ADDR=http://last-civilization_vault:8200
      - VAULT_TOKEN=last-civilization
    volumes:
      - ./vault/vault_init.sh:/vault_init.sh
    depends_on:
      - "last-civilization_vault"
    command: /bin/sh -c "chmod a+x ./vault_init.sh && ./vault_init.sh"
  last-civilization_postgresql_user_master:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_DATABASE=last-civilization_user_db
  last-civilization_postgresql_user_slave:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5432'
    depends_on:
      - last-civilization_postgresql_user_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_MASTER_HOST=last-civilization_postgresql_user_master
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  last-civilization_keycloak:
    image: quay.io/keycloak/keycloak:16.0.0
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=last-civilization
      - KEYCLOAK_PASSWORD=last-civilization
      - KK_TO_RMQ_URL=last-civilization_rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=last-civilization
      - KK_TO_RMQ_PASSWORD=last-civilization
      - KK_TO_RMQ_VHOST=/
    volumes:
      - ./keycloak/realm-export.json:/data/import/realm-export.json
      - ./keycloak/login:/opt/jboss/keycloak/themes/custom/login
      - ./keycloak/keycloak-to-rabbit-3.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-3.0.jar
    command:
      - "-Dkeycloak.import=/data/import/realm-export.json"
  last-civilization_rabbitmq:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=last-civilization
      - RABBITMQ_DEFAULT_PASS=last-civilization
      - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
  last-civilization_postgresql_payment_master:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_DATABASE=last-civilization_payment_db
  last-civilization_postgresql_payment_slave:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5435:5432'
    depends_on:
      - last-civilization_postgresql_payment_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_MASTER_HOST=last-civilization_postgresql_payment_master
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  last-civilization_postgresql_stats_master:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5436:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_DATABASE=last-civilization_stats_db
  last-civilization_postgresql_stats_slave:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5437:5432'
    depends_on:
      - last-civilization_postgresql_stats_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_MASTER_HOST=last-civilization_postgresql_stats_master
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16