version: '3.3'

services:
  last-civilization_vault:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    image: vault:1.11.2
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id last-civilization
  last-civilization_vault_setup:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    image: vault:1.11.2
    environment:
      - VAULT_ADDR=http://last-civilization_vault:8200
      - VAULT_TOKEN=last-civilization
    volumes:
      - ./vault/vault_init.sh:/vault_init.sh
    depends_on:
      - "last-civilization_vault"
    command: /bin/sh -c "chmod a+x ./vault_init.sh && ./vault_init.sh"
  last-civilization_postgresql_master:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_DATABASE=last-civilization_db
  last-civilization_postgresql_slave:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5432'
    depends_on:
      - last-civilization_postgresql_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_MASTER_HOST=last-civilization_postgresql_master
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  last-civilization_keycloak:
    image: quay.io/keycloak/keycloak:16.0.0
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=last-civilization
      - KEYCLOAK_PASSWORD=last-civilization
      - KK_TO_RMQ_URL=last-civilization_rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=last-civilization
      - KK_TO_RMQ_PASSWORD=last-civilization
      - KK_TO_RMQ_VHOST=/
    volumes:
      - ./keycloak/realm-export.json:/data/import/realm-export.json
      - ./keycloak/login:/opt/jboss/keycloak/themes/custom/login
      - ./keycloak/keycloak-to-rabbit-3.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-3.0.jar
    command:
      - "-Dkeycloak.import=/data/import/realm-export.json"
  last-civilization_rabbitmq:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=last-civilization
      - RABBITMQ_DEFAULT_PASS=last-civilization
      - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq.conf
  last-civilization_cassandra:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    image: cassandra:3.11
    ports:
      - "9042:9042"
  last-civilization_prometheus:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9191:9090'
  last-civilization_node-exporter:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    image: prom/node-exporter
    ports:
      - '9100:9100'
  last-civilization_cadence:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
    image: ubercadence/server:master-auto-setup
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
      - "7833:7833"
    environment:
      - "CASSANDRA_SEEDS=last-civilization_cassandra"
      - "PROMETHEUS_ENDPOINT_0=0.0.0.0:8000"
      - "PROMETHEUS_ENDPOINT_1=0.0.0.0:8001"
      - "PROMETHEUS_ENDPOINT_2=0.0.0.0:8002"
      - "PROMETHEUS_ENDPOINT_3=0.0.0.0:8003"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - last-civilization_cassandra
      - last-civilization_prometheus
  last-civilization_cadence-web:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12
    image: ubercadence/web:latest
    environment:
      - "CADENCE_TCHANNEL_PEERS=last-civilization_cadence:7933"
    ports:
      - "8088:8088"
    depends_on:
      - last-civilization_cadence
  last-civilization_grafana:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.13
    image: grafana/grafana
    user: "1000"
    depends_on:
      - last-civilization_prometheus
    ports:
      - '3000:3000'
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16