version: '3.3'

services:
  last-civilization_vault:
    image: vault:1.11.2
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id last-civilization
  last-civilization_vault_setup:
    image: vault:1.11.2
    environment:
      - VAULT_ADDR=http://last_civilization_vault:8200
      - VAULT_TOKEN=last-civilization
    volumes:
      - ./vault_init.sh:/vault_init.sh
    depends_on:
      - "last-civilization_vault"
    command: /bin/sh -c "chmod a+x ./vault_init.sh && ./vault_init.sh"
  last-civilization_postgresql_user_master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_DATABASE=last-civilization_user_db
  last-civilization_postgresql_user_slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5432'
    depends_on:
      - last-civilization_postgresql_user_master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_last-civilization
      - POSTGRESQL_REPLICATION_PASSWORD=repl_last-civilization
      - POSTGRESQL_MASTER_HOST=last_civilization_postgresql_user_master
      - POSTGRESQL_USERNAME=last-civilization
      - POSTGRESQL_PASSWORD=last-civilization
      - POSTGRESQL_MASTER_PORT_NUMBER=5432